version: '2'
services:
  cloudinary:
    image: romajs/cloudinary-mock:latest
    ports:
      - "9080:9080"
      - "9443:9443"
  dev:
    build: .
    links:
      - cloudinary
      - mongodb
      - unleash-server
    ports:
      - "8000:8000"
    restart: "on-failure"
    volumes:
      - ./:/app
    command: |
      sh -c "
        while ! nc -z unleash-server 4242; do
          echo 'Waiting for unleash-server:4242 connection to be available...'
          sleep 1
        done
        npm run start-dev"
  mongodb:
    image: mongo:3.6.4-jessie
    ports:
      - "27017:27017"
  postgresdb:
    expose:
      - "5432"
    image: postgres:10-alpine
  unleash-server:
    image: romajs/unleash-server
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: postgres://postgres:unleash@postgresdb/postgres
    links:
      - postgresdb
    command: |
      sh -c "
        while ! nc -z postgresdb 5432; do
          echo 'Waiting for postgres connection to be available...'
          sleep 1
        done
        npm run start"

