version: '2'
services:
  dev:
    build: .
    links:
      - cloudinary
      - mongodb
    ports:
      - "8000:8000"
    restart: "on-failure"
    volumes:
      - ./:/app
  cloudinary:
    image: romajs/cloudinary-mock:latest
    ports:
      - "9080:9080"
      - "9443:9443"
  mongodb:
    image: mongo:3.6.4-jessie
    ports:
      - "27017:27017"
