FROM node:6.14.2-alpine

WORKDIR /app

ENV ADMIN_AUTH_PASSWORD=""
ENV ADMIN_AUTH_USERNAME=""
ENV ADMIN_BASE_PATH="/"
ENV CLOUDINARY_UPLOAD_PREFIX="https://cloudinary:9443"
ENV CLOUDINARY_URL="cloudinary://api_key:api_secret@laranjo-api"
ENV GOOGLE_HANGOUTS_CHAT_AUTH_TOKEN=""
ENV GOOGLE_HANGOUTS_CHAT_BASE_PATH="/"
ENV HOST="0.0.0.0"
ENV LOGGER_LEVEL="silly"
ENV MONGODB_URI="mongodb://mongodb:27017/laranjo-api"
ENV NODE_TLS_REJECT_UNAUTHORIZED="0"
ENV PORT="8000"
ENV ROOT_BASE_PATH="/"
ENV UNLEASH_URL="http://unleash-server:4242/api/"

EXPOSE 8000

CMD ["npm", "run", "start-dev"]