version: '2'
services:

  cloudinary:
    image: romajs/cloudinary-mock:latest
    ports:
      - "9080:9080"
      - "9443:9443"

  mongodb:
    image: mongo:3.6.4-jessie
    ports:
      - "27017:27017"

  postgresdb:
    expose:
      - "5432"
    image: postgres:10-alpine

  unleash-server:
    command: |
      sh -c "
        while ! nc -z postgresdb 5432; do
          echo 'Waiting for postgres connection to be available...'
          sleep 1
        done
        npm run start"
    image: romajs/unleash-server
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: postgres://postgres:unleash@postgresdb/postgres
    links:
      - postgresdb
      
  web:
    build: .
    command: |
      sh -c "
        while ! nc -z unleash-server 4242; do
          echo 'Waiting for unleash-server:4242 connection to be available...'
          sleep 1
        done
        npm run start-dev"
    environment:
      ADMIN_BASE_PATH: /
      ADMIN_UPLOAD_MAX_FILE_SIZE: 2MB
      CLOUDINARY_UPLOAD_PREFIX: https://cloudinary:9443
      CLOUDINARY_URL: cloudinary://api_key:api_secret@laranjo-api
      GOOGLE_HANGOUTS_CHAT_BASE_PATH: /
      HOST: 0.0.0.0
      LOGGER_LEVEL: silly
      MONGODB_URI: mongodb://mongodb:27017/laranjo-api
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      PORT: 8000
      ROOT_BASE_PATH:
      UNLEASH_URL: "http://unleash-server:4242/api/"
    links:
      - cloudinary
      - mongodb
    ports:
      - "8000:8000"
    restart: "on-failure"
    volumes:
      - ./:/app
